project_name       = "Terraform Deployment Blog"
description        = "This is the project created using Terraform"
visibility         = "private"
version_control    = "Git"
work_item_template = "Agile"
build_name         = "DIBuild"
repo_name = "Imported Repo"
repo_source_url = "https://github.com/bhatts11/ADO-Terraform.git"